apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-container
          image: ghcr.io/smart-home-with-k8s-and-microservices/device-management-service-web:v2
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: host-dev
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_RAWIO
          env:
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-superuser-username
                  key: token
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-superuser-password
                  key: token
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: django-superuser-mail
                  key: token
            - name: POSTGRES_NAME
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-username
                  key: token
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: token
            - name: POSTGRES_PORT
              value: "5432"
            - name: MQTT_BROKER
              value: mqttbroker
            - name: MQTT_PORT
              value: "1883"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "home_automation"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "sensor_data_bucket"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-admin-token
                  key: token
            - name: DOCKER_INFLUXDB_HOST_TYPE
              value: "http"
            - name: DOCKER_INFLUXDB_HOST
              value: "influxdb"
            - name: DOCKER_INFLUXDB_PORT
              value: "8086"
      volumes:
        - name: host-dev
          hostPath:
            path: /dev/ttyUSB0
